easy_admin:
    site_name: Pat&Soaze

    design:
        menu:
            - { route: 'home', label: 'Back to the website', icon: 'home' }
            - { entity: 'Aquarelle', label: 'Aquarelles', icon: 'map-marker' }
            - { entity: 'Photo', label: 'Photos', icon: 'comments' }
            - { entity: 'Admin', label: 'Utilisateurs', icon: 'comments' }
            - { entity: 'AlbumPhoto', label: 'Album photo', icon: 'comments' }
            - { entity: 'Actualite', label: 'Actualites', icon: 'comments' }
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'
    entities:
        - App\Entity\Aquarelle
            list:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.aquarelle_images%' }
            show:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.aquarelle_images%' }
#            form:
#                fields:
#                    - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.aquarelle_images%' }

        - App\Entity\Photo
            list:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.photo_images%' }
            show:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.photo_images%' }

        - App\Entity\Admin
            list:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.admin_images%' }
            show:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.admin_images%' }

        - App\Entity\AlbumPhoto
            list:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.photo_images%' }
            show:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.photo_images%' }
            form:
                fields:
                    - { property: 'photo', type: 'collection', type_options: {entry_type: 'App\Form\PhotoType', by_reference: false} }
        - App\Entity\Actualite
            list:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.actualite_images%' }
                    - { property: 'fichier', type: 'vich_file', base_path: '%app.path.actualite_fichiers%' }
            show:
                fields:
                    - { property: 'image', type: 'vich_image', base_path: '%app.path.actualite_images%' }
                    - { property: 'fichier', type: 'vich_file', base_path: '%app.path.actualite_fichiers%' }


#

#        Comment:
#            class: App\Entity\Comment
#            list:
#                fields:
#                    - author
#                    - { property: 'email', type: 'email' }
#                    - { property: 'photoFilename', type: 'image', 'base_path': "/uploads/photos", label: 'Photo' }
#                    - state
#                    - { property: 'createdAt', type: 'datetime' }
#                sort: ['createdAt', 'ASC']
#                filters: ['conference']
#            edit:
#                fields:
#                    - { property: 'conference' }
#                    - { property: 'createdAt', type: datetime, type_options: { attr: { readonly: true } } }
#                    - 'author'
#                    - { property: 'state' }
#                    - { property: 'email', type: 'email' }
#                    - text