#index:
#    path: /
#    controller: App\Controller\DefaultController::index


logout:
  path: /logout


#easyAdmin_bundle:
#  # loads routes from the YAML or XML files found in some bundle directory
#  resource: '@AppBundle/Resources/config/routing/public/'
#  type:     directory

